#!/usr/bin/env bash

NUM=$1
ON=$2
OFF=$3

[[ "$NUM" =~ ^[0-9]+$ ]] || NUM=1
[[ "$ON" =~ ^[0-9]+\.?[0-9]*$ ]] || ON=0
[[ "$OFF" =~ ^[0-9]+\.?[0-9]*$ ]] || OFF=0

shortest_beeptrain() {
	for I in $(seq $NUM); do
		beep $ON
	done
}

delayed_beeptrain() {
	for I in $(seq $NUM); do
		beep $ON
		sleep $OFF
	done
}

[ "$OFF" == "0" ] && shortest_beeptrain || delayed_beeptrain
