#!/usr/bin/env bash


SOUND_OK="-s gamelan"
SOUND_FAIL="-s siren"

function pause {
	# Time set happens quick so pause briefly so the beeps don't blend in (Artificial delays... eww. Should come up with an alternative.... TODO)
	sleep 0.5
}

function sendTimeToSynScan {
	pause
	# Set the SynScan time. Using UTC. Maybe I should do local? Thinking about it.
	if send_time_to_synscan; then
		beep $BEEPS 100 100
		message $SOUND_OK -t "Sent Time to SynScan" "Sent date and time to SynScan."
	else
		beep $BEEPS 1000 100
		message -p 1 $SOUND_FAIL -t "Time to SynScan Failure!" "Could not send date and time to SynScan! Please set the date and time in SynScan manually!!!"
	fi
}

function message {
	if grep -P ' -p [12] ' &>/dev/null <<< "$@"; then
		log_warn "${@: -1}"
	else
		log_info "${@: -1}"
	fi
	pushover.sh "$@"
	JOBS=$(jobs | wc -l)
	[ "$JOBS" -gt 0 ] && echo
	echo "$(date) :: ${@: -1}"
}

# Signal that initialization is starting
beeptrain $(seq 40)

# Start fake gpsd for testing
#systemctl stop gpsd; gpsfake -q -c 0.3 /root/gps.recorded &

# Set low latency mode on the serial interfaces
setserial /dev/ttyS0 low_latency
setserial /dev/ttyUSB0 low_latency

# Enable masquarading and ip pass-through
# This is done now with Astra/rules.v4 link in /etc/iptables/ and Astra/95-sysctl-astra.conf link in /etc/sysctl.d/
#enable_pat_routing


message $SOUND_OK -t "Astra Initializing..." "Starting telescope configuration. Standby..."

# Set system time from the GPS (my gps has a battery backed RTC - Adafruit Ultimate GPS Breakout - 66 channel w/10 Hz updates (Version 3)

message $SOUND_OK -t "Acquiring GPS Time" "Standby for GPS time acquisition. This may take many minutes. You can skip this step by rotating the telescope 5° around its azimuth axis."

BEEPS=1
run_until_axis_move wait_for_gps_time
ERROR=$?
TIME=0
if [ "$ERROR" -eq 0 ]; then 
	beep $BEEPS 100 100
	message $SOUND_OK -t "Acquired GPS Time" "Acquired date and time from the GPS. Astra time is: $(date)"
	TIME=1
elif [ "$ERROR" -eq 127 ]; then  
	beep $BEEPS 1000 100
	message -p 1 $SOUND_FAIL -t "GPS Time Acquisition Cancelled" "GPS time acquisition cancelled by an azimuth axis move!"
else
	beep $BEEPS 1000 100
	message -p 1 $SOUND_FAIL -t "GPS Time Acquisition Failed" "Failed to obtain GPS time! It was not interrupted by an azimuth axis move!"
fi

if [ "$TIME" -eq 0 ]; then 
	message $SOUND_OK -t "Acquiring RTC Time" "Standby for RTC time acquisition. This may take many minutes. You can skip this step by rotating the telescope 5° around its azimuth axis."
	run_until_axis_move wait_for_rtc_time
	ERROR=$?
	if [ "$ERROR" -eq 0 ]; then 
		beep $BEEPS 100 100
		message $SOUND_OK -t "Acquired RTC Time" "Retrieved date and time from the RTC. Astra time is: $(date)"
		TIME=1
	elif [ "$ERROR" -eq 127 ]; then  
		beep $BEEPS 1000 100
		message -p 1 $SOUND_FAIL -t "RTC Time Acquisition Cancelled" "RTC time wait cancelled by an azimuth axis move!"
	else
		beep $BEEPS 1000 100
		message -p 1 $SOUND_FAIL -t "RTC Time Acquisition Failed" "Failed to obtain RTC time! It was not interrupted by an azimuth axis move!"
	fi

fi

BEEPS=2
if [ "$TIME" -eq 1 ]; then
	sendTimeToSynScan
else
	beep $BEEPS 1000 100
	message -p 1 $SOUND_FAIL -t "NOT Sending Time To SynScan" "Astra was unable to acquire time from neither the GPS nor the RTC. Set it in SynScan manually!!!"
fi
	
message $SOUND_OK -t "Waiting for GPS Fix" "Standby for GPS Acquisition. This may take many minutes. You can skip this step by rotating the telescope 5° around its azimuth axis."

BEEPS=3
# Wait for and send gps location to SynScan.
 run_until_axis_move send_location_to_synscan
ERROR=$?

if [ "$ERROR" -eq 0 ]; then
	beep $BEEPS 100 100
	message $SOUND_OK -t "Sent GPS Data to SynScan" "Sent GPS Latitude and Longitude to SynScan."
elif [ "$ERROR" -eq 127 ]; then
	beep $BEEPS 1000 100
	message -p 1 $SOUND_FAIL -p 1 -t "GPS Sync Canceled" "Wait for GPS data and sync to SynScan cancelled by an azimuth axis move! Please enter your Latitude and Logitude in SynScan manually!!!"
else
	beep $BEEPS 1000 100
	message -p 1 $SOUND_FAIL -p 1 -t "GPS Sync Failed" "Could not send GPS Latitude and Longitude to SynScan! Likely due to serial comms issue with SynScan. It was not interrupted by an azimuth axis move! Please enter your Latitude and Logitude in SynScan manually!!!"
fi

# Now that we're done talking to the mount allow external traffic in to control the telescope (SkySafari, Stellarium, etc.)
allow_ser2net_port

pause

BEEPS=4
# Check and signal internet connectivity
internet_check && beep $BEEPS 100 100 || beep $BEEPS 1000 100

CONNECTION_INFO="$(get_connection_info)"

# Signal end of initialization
beep 50 10 10
message -p 2 -r 180 -e 3600 -s echo "Initialization Complete!" $'The telescope is all yours. You can now perform star alignment. The serial over IP proxy is online. You can control the telescope via:\n\n'"$CONNECTION_INFO"$'\n\nClear skyes!'
