#!/usr/bin/env bash

set -e

#readonly serial=/dev/ttyS0
timeout=5
MAX_RETRIES=5

# set the serial port speed
#stty -F ${serial} 9600

# get the date in the order the protocol calls for
dtm="$(date -u '+%_H %_M %_S %_m %_d %_y 0 0')"

# H is the command char; the following 8 bytes are the date/time
HEX="\\\\x%02X"
unset FORMAT
for i in {1..8}; do FORMAT="${FORMAT}${HEX}"; done
hex_text="$(printf "H${FORMAT}" ${dtm})"

#echo "Writing time to HC: '${hex_text}'
#timeout $timeout echo -ne "${hex_text}" > ${serial}
RETRIES=0
RESPONSE=""

while [ "$RESPONSE" != "#" ] && [ "$RETRIES" -le "$MAX_RETRIES" ] ; do
	((RETRIES=$RETRIES+1))
	RESPONSE=$(echo -ne "${hex_text}" | netcat -w $timeout -W 1 127.0.0.1 4030)
done

RET_MSG=""
[ "$RETRIES" -gt 1 ] && RET_MSG="after $RETRIES retries."

if [ "$RESPONSE" == "#" ]; then
	log_info "Time ${dtm} sent to telescope $RET_MSG"
	exit 0
else
	log_warn "Time ${dtm} send to delescope FAILED $RET_MSG"
	exit 1
fi
