#!/usr/bin/env bash

set -e


#GPSTIME=$(gpspipe -r | grep -m1 GPZDA | perl -pe 's/^\$GPZDA,(\d\d)(\d\d)(\d\d)\.\d\d\d,(\d\d),(\d\d),(\d\d\d\d),.*/\6-\5-\4 \1:\2:\3 UTC/g')

SENTENCE=$(gpspipe -r | grep -Pm1 "GPZDA|GPRMC" )

[[ "$SENTENCE" =~ GPZDA ]] && GPSTIME=$(echo "$SENTENCE" | perl -pe 's/^\$GPZDA,(\d\d)(\d\d)(\d\d)\.\d\d\d,(\d\d),(\d\d),(\d\d\d\d),.*/\6-\5-\4 \1:\2:\3 UTC/g')
[[ "$SENTENCE" =~ GPRMC ]] && GPSTIME=$(echo "$SENTENCE" | perl -pe 's/^\$GPRMC,(\d\d)(\d\d)(\d\d)\.\d\d\d,[^,]+,[^,]+,[^,]+,[^,]+,[^,]+,[^,]+,[^,]+,(\d\d)(\d\d)(\d\d),.*/20\6-\5-\4 \1:\2:\3 UTC/g')

date -s "$GPSTIME"

log_info "RPi time set from GPS"
