#!/usr/bin/env bash

set -e

GPSTIME=$(gpspipe -r | grep -m1 GPZDA | perl -pe 's/^\$GPZDA,(\d\d)(\d\d)(\d\d)\.\d\d\d,(\d\d),(\d\d),(\d\d\d\d),.*/\6-\5-\4 \1:\2:\3 UTC/g')
date -s "$GPSTIME"

log_info "RPi time set from GPS"
